diagram_fact(align, cell_13, "left").
diagram_fact(align, cell_24, "left").
diagram_fact(align, cell_29, "left").
diagram_fact(align, cell_63, "left").
diagram_fact(align, cell_68, "left").
diagram_fact(align, cell_8, "left").
diagram_fact(align, cell_88, "left").
diagram_fact(align, cell_93, "left").
diagram_fact(as, cell_10, "geometry").
diagram_fact(as, cell_100, "geometry").
diagram_fact(as, cell_101, "geometry").
diagram_fact(as, cell_102, "geometry").
diagram_fact(as, cell_103, "geometry").
diagram_fact(as, cell_104, "geometry").
diagram_fact(as, cell_105, "geometry").
diagram_fact(as, cell_11, "geometry").
diagram_fact(as, cell_111, "geometry").
diagram_fact(as, cell_112, "geometry").
diagram_fact(as, cell_113, "geometry").
diagram_fact(as, cell_114, "geometry").
diagram_fact(as, cell_115, "geometry").
diagram_fact(as, cell_116, "geometry").
diagram_fact(as, cell_117, "geometry").
diagram_fact(as, cell_118, "geometry").
diagram_fact(as, cell_119, "geometry").
diagram_fact(as, cell_12, "geometry").
diagram_fact(as, cell_120, "geometry").
diagram_fact(as, cell_121, "geometry").
diagram_fact(as, cell_122, "geometry").
diagram_fact(as, cell_123, "geometry").
diagram_fact(as, cell_124, "geometry").
diagram_fact(as, cell_13, "geometry").
diagram_fact(as, cell_14, "geometry").
diagram_fact(as, cell_15, "geometry").
diagram_fact(as, cell_16, "geometry").
diagram_fact(as, cell_22, "geometry").
diagram_fact(as, cell_23, "geometry").
diagram_fact(as, cell_24, "geometry").
diagram_fact(as, cell_25, "geometry").
diagram_fact(as, cell_26, "geometry").
diagram_fact(as, cell_27, "geometry").
diagram_fact(as, cell_28, "geometry").
diagram_fact(as, cell_29, "geometry").
diagram_fact(as, cell_30, "geometry").
diagram_fact(as, cell_31, "geometry").
diagram_fact(as, cell_32, "geometry").
diagram_fact(as, cell_33, "geometry").
diagram_fact(as, cell_39, "geometry").
diagram_fact(as, cell_40, "geometry").
diagram_fact(as, cell_41, "geometry").
diagram_fact(as, cell_42, "geometry").
diagram_fact(as, cell_43, "geometry").
diagram_fact(as, cell_44, "geometry").
diagram_fact(as, cell_45, "geometry").
diagram_fact(as, cell_46, "geometry").
diagram_fact(as, cell_47, "geometry").
diagram_fact(as, cell_48, "geometry").
diagram_fact(as, cell_49, "geometry").
diagram_fact(as, cell_50, "geometry").
diagram_fact(as, cell_51, "geometry").
diagram_fact(as, cell_52, "geometry").
diagram_fact(as, cell_53, "geometry").
diagram_fact(as, cell_54, "geometry").
diagram_fact(as, cell_55, "geometry").
diagram_fact(as, cell_6, "geometry").
diagram_fact(as, cell_61, "geometry").
diagram_fact(as, cell_62, "geometry").
diagram_fact(as, cell_63, "geometry").
diagram_fact(as, cell_64, "geometry").
diagram_fact(as, cell_65, "geometry").
diagram_fact(as, cell_66, "geometry").
diagram_fact(as, cell_67, "geometry").
diagram_fact(as, cell_68, "geometry").
diagram_fact(as, cell_69, "geometry").
diagram_fact(as, cell_7, "geometry").
diagram_fact(as, cell_70, "geometry").
diagram_fact(as, cell_71, "geometry").
diagram_fact(as, cell_72, "geometry").
diagram_fact(as, cell_73, "geometry").
diagram_fact(as, cell_74, "geometry").
diagram_fact(as, cell_75, "geometry").
diagram_fact(as, cell_76, "geometry").
diagram_fact(as, cell_77, "geometry").
diagram_fact(as, cell_78, "geometry").
diagram_fact(as, cell_79, "geometry").
diagram_fact(as, cell_8, "geometry").
diagram_fact(as, cell_80, "geometry").
diagram_fact(as, cell_86, "geometry").
diagram_fact(as, cell_87, "geometry").
diagram_fact(as, cell_88, "geometry").
diagram_fact(as, cell_89, "geometry").
diagram_fact(as, cell_9, "geometry").
diagram_fact(as, cell_90, "geometry").
diagram_fact(as, cell_91, "geometry").
diagram_fact(as, cell_92, "geometry").
diagram_fact(as, cell_93, "geometry").
diagram_fact(as, cell_94, "geometry").
diagram_fact(as, cell_95, "geometry").
diagram_fact(as, cell_96, "geometry").
diagram_fact(as, cell_97, "geometry").
diagram_fact(as, cell_98, "geometry").
diagram_fact(as, cell_99, "geometry").
diagram_fact(aspect, cell_10, "fixed").
diagram_fact(aspect, cell_114, "fixed").
diagram_fact(aspect, cell_116, "fixed").
diagram_fact(aspect, cell_118, "fixed").
diagram_fact(aspect, cell_119, "fixed").
diagram_fact(aspect, cell_12, "fixed").
diagram_fact(aspect, cell_15, "fixed").
diagram_fact(aspect, cell_16, "fixed").
diagram_fact(aspect, cell_26, "fixed").
diagram_fact(aspect, cell_28, "fixed").
diagram_fact(aspect, cell_31, "fixed").
diagram_fact(aspect, cell_32, "fixed").
diagram_fact(aspect, cell_42, "fixed").
diagram_fact(aspect, cell_44, "fixed").
diagram_fact(aspect, cell_46, "fixed").
diagram_fact(aspect, cell_47, "fixed").
diagram_fact(aspect, cell_65, "fixed").
diagram_fact(aspect, cell_67, "fixed").
diagram_fact(aspect, cell_70, "fixed").
diagram_fact(aspect, cell_71, "fixed").
diagram_fact(aspect, cell_90, "fixed").
diagram_fact(aspect, cell_92, "fixed").
diagram_fact(aspect, cell_95, "fixed").
diagram_fact(aspect, cell_96, "fixed").
diagram_fact(cell, cell_10, "").
diagram_fact(cell, cell_100, "").
diagram_fact(cell, cell_101, "").
diagram_fact(cell, cell_102, "").
diagram_fact(cell, cell_103, "").
diagram_fact(cell, cell_104, "").
diagram_fact(cell, cell_105, "").
diagram_fact(cell, cell_109, "").
diagram_fact(cell, cell_11, "").
diagram_fact(cell, cell_110, "").
diagram_fact(cell, cell_111, "").
diagram_fact(cell, cell_112, "").
diagram_fact(cell, cell_113, "").
diagram_fact(cell, cell_114, "").
diagram_fact(cell, cell_115, "").
diagram_fact(cell, cell_116, "").
diagram_fact(cell, cell_117, "").
diagram_fact(cell, cell_118, "").
diagram_fact(cell, cell_119, "").
diagram_fact(cell, cell_12, "").
diagram_fact(cell, cell_120, "").
diagram_fact(cell, cell_121, "").
diagram_fact(cell, cell_122, "").
diagram_fact(cell, cell_123, "").
diagram_fact(cell, cell_124, "").
diagram_fact(cell, cell_13, "").
diagram_fact(cell, cell_14, "").
diagram_fact(cell, cell_15, "").
diagram_fact(cell, cell_16, "").
diagram_fact(cell, cell_20, "").
diagram_fact(cell, cell_21, "").
diagram_fact(cell, cell_22, "").
diagram_fact(cell, cell_23, "").
diagram_fact(cell, cell_24, "").
diagram_fact(cell, cell_25, "").
diagram_fact(cell, cell_26, "").
diagram_fact(cell, cell_27, "").
diagram_fact(cell, cell_28, "").
diagram_fact(cell, cell_29, "").
diagram_fact(cell, cell_30, "").
diagram_fact(cell, cell_31, "").
diagram_fact(cell, cell_32, "").
diagram_fact(cell, cell_33, "").
diagram_fact(cell, cell_37, "").
diagram_fact(cell, cell_38, "").
diagram_fact(cell, cell_39, "").
diagram_fact(cell, cell_4, "").
diagram_fact(cell, cell_40, "").
diagram_fact(cell, cell_41, "").
diagram_fact(cell, cell_42, "").
diagram_fact(cell, cell_43, "").
diagram_fact(cell, cell_44, "").
diagram_fact(cell, cell_45, "").
diagram_fact(cell, cell_46, "").
diagram_fact(cell, cell_47, "").
diagram_fact(cell, cell_48, "").
diagram_fact(cell, cell_49, "").
diagram_fact(cell, cell_5, "").
diagram_fact(cell, cell_50, "").
diagram_fact(cell, cell_51, "").
diagram_fact(cell, cell_52, "").
diagram_fact(cell, cell_53, "").
diagram_fact(cell, cell_54, "").
diagram_fact(cell, cell_55, "").
diagram_fact(cell, cell_59, "").
diagram_fact(cell, cell_6, "").
diagram_fact(cell, cell_60, "").
diagram_fact(cell, cell_61, "").
diagram_fact(cell, cell_62, "").
diagram_fact(cell, cell_63, "").
diagram_fact(cell, cell_64, "").
diagram_fact(cell, cell_65, "").
diagram_fact(cell, cell_66, "").
diagram_fact(cell, cell_67, "").
diagram_fact(cell, cell_68, "").
diagram_fact(cell, cell_69, "").
diagram_fact(cell, cell_7, "").
diagram_fact(cell, cell_70, "").
diagram_fact(cell, cell_71, "").
diagram_fact(cell, cell_72, "").
diagram_fact(cell, cell_73, "").
diagram_fact(cell, cell_74, "").
diagram_fact(cell, cell_75, "").
diagram_fact(cell, cell_76, "").
diagram_fact(cell, cell_77, "").
diagram_fact(cell, cell_78, "").
diagram_fact(cell, cell_79, "").
diagram_fact(cell, cell_8, "").
diagram_fact(cell, cell_80, "").
diagram_fact(cell, cell_84, "").
diagram_fact(cell, cell_85, "").
diagram_fact(cell, cell_86, "").
diagram_fact(cell, cell_87, "").
diagram_fact(cell, cell_88, "").
diagram_fact(cell, cell_89, "").
diagram_fact(cell, cell_9, "").
diagram_fact(cell, cell_90, "").
diagram_fact(cell, cell_91, "").
diagram_fact(cell, cell_92, "").
diagram_fact(cell, cell_93, "").
diagram_fact(cell, cell_94, "").
diagram_fact(cell, cell_95, "").
diagram_fact(cell, cell_96, "").
diagram_fact(cell, cell_97, "").
diagram_fact(cell, cell_98, "").
diagram_fact(cell, cell_99, "").
diagram_fact(diagram, diagram_1, "").
diagram_fact(diagram, diagram_106, "").
diagram_fact(diagram, diagram_17, "").
diagram_fact(diagram, diagram_34, "").
diagram_fact(diagram, diagram_56, "").
diagram_fact(diagram, diagram_81, "").
diagram_fact(edge, cell_113, 1).
diagram_fact(edge, cell_117, 1).
diagram_fact(edge, cell_14, 1).
diagram_fact(edge, cell_25, 1).
diagram_fact(edge, cell_30, 1).
diagram_fact(edge, cell_41, 1).
diagram_fact(edge, cell_45, 1).
diagram_fact(edge, cell_64, 1).
diagram_fact(edge, cell_69, 1).
diagram_fact(edge, cell_89, 1).
diagram_fact(edge, cell_9, 1).
diagram_fact(edge, cell_94, 1).
diagram_fact(edgeStyle, cell_113, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_117, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_14, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_25, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_30, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_41, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_45, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_64, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_69, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_89, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_9, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_94, "orthogonalEdgeStyle").
diagram_fact(entryDx, cell_113, 0).
diagram_fact(entryDx, cell_117, 0).
diagram_fact(entryDx, cell_14, 0).
diagram_fact(entryDx, cell_25, 0).
diagram_fact(entryDx, cell_30, 0).
diagram_fact(entryDx, cell_41, 0).
diagram_fact(entryDx, cell_45, 0).
diagram_fact(entryDx, cell_64, 0).
diagram_fact(entryDx, cell_69, 0).
diagram_fact(entryDx, cell_89, 0).
diagram_fact(entryDx, cell_9, 0).
diagram_fact(entryDx, cell_94, 0).
diagram_fact(entryDy, cell_113, 0).
diagram_fact(entryDy, cell_117, 0).
diagram_fact(entryDy, cell_14, 0).
diagram_fact(entryDy, cell_25, 0).
diagram_fact(entryDy, cell_30, 0).
diagram_fact(entryDy, cell_41, 0).
diagram_fact(entryDy, cell_45, 0).
diagram_fact(entryDy, cell_64, 0).
diagram_fact(entryDy, cell_69, 0).
diagram_fact(entryDy, cell_89, 0).
diagram_fact(entryDy, cell_9, 0).
diagram_fact(entryDy, cell_94, 0).
diagram_fact(entryX, cell_113, 0).
diagram_fact(entryX, cell_117, 0).
diagram_fact(entryX, cell_14, 0).
diagram_fact(entryX, cell_25, 0).
diagram_fact(entryX, cell_30, 0).
diagram_fact(entryX, cell_41, 0).
diagram_fact(entryX, cell_45, 0).
diagram_fact(entryX, cell_64, 0).
diagram_fact(entryX, cell_69, 0).
diagram_fact(entryX, cell_89, 0).
diagram_fact(entryX, cell_9, 0).
diagram_fact(entryX, cell_94, 0).
diagram_fact(entryY, cell_113, 0.5).
diagram_fact(entryY, cell_117, 0.5).
diagram_fact(entryY, cell_14, 0.5).
diagram_fact(entryY, cell_25, 0.5).
diagram_fact(entryY, cell_30, 0.5).
diagram_fact(entryY, cell_41, 0.5).
diagram_fact(entryY, cell_45, 0.5).
diagram_fact(entryY, cell_64, 0.5).
diagram_fact(entryY, cell_69, 0.5).
diagram_fact(entryY, cell_89, 0.5).
diagram_fact(entryY, cell_9, 0.5).
diagram_fact(entryY, cell_94, 0.5).
diagram_fact(exitDx, cell_117, 0).
diagram_fact(exitDx, cell_14, 0).
diagram_fact(exitDx, cell_30, 0).
diagram_fact(exitDx, cell_45, 0).
diagram_fact(exitDx, cell_69, 0).
diagram_fact(exitDx, cell_94, 0).
diagram_fact(exitDy, cell_117, 0).
diagram_fact(exitDy, cell_14, 0).
diagram_fact(exitDy, cell_30, 0).
diagram_fact(exitDy, cell_45, 0).
diagram_fact(exitDy, cell_69, 0).
diagram_fact(exitDy, cell_94, 0).
diagram_fact(exitX, cell_117, 1).
diagram_fact(exitX, cell_14, 1).
diagram_fact(exitX, cell_30, 1).
diagram_fact(exitX, cell_45, 1).
diagram_fact(exitX, cell_69, 1).
diagram_fact(exitX, cell_94, 1).
diagram_fact(exitY, cell_117, 0.5).
diagram_fact(exitY, cell_14, 0.5).
diagram_fact(exitY, cell_30, 0.5).
diagram_fact(exitY, cell_45, 0.5).
diagram_fact(exitY, cell_69, 0.5).
diagram_fact(exitY, cell_94, 0.5).
diagram_fact(fillColor, cell_10, "#fff2cc").
diagram_fact(fillColor, cell_11, "#dae8fc").
diagram_fact(fillColor, cell_112, "#dae8fc").
diagram_fact(fillColor, cell_114, "#fff2cc").
diagram_fact(fillColor, cell_115, "#dae8fc").
diagram_fact(fillColor, cell_116, "#d5e8d4").
diagram_fact(fillColor, cell_118, "#d5e8d4").
diagram_fact(fillColor, cell_119, "#d5e8d4").
diagram_fact(fillColor, cell_12, "#d5e8d4").
diagram_fact(fillColor, cell_13, "#f8cecc").
diagram_fact(fillColor, cell_15, "#d5e8d4").
diagram_fact(fillColor, cell_16, "#d5e8d4").
diagram_fact(fillColor, cell_23, "#dae8fc").
diagram_fact(fillColor, cell_24, "#f8cecc").
diagram_fact(fillColor, cell_26, "#fff2cc").
diagram_fact(fillColor, cell_27, "#dae8fc").
diagram_fact(fillColor, cell_28, "#d5e8d4").
diagram_fact(fillColor, cell_29, "#f8cecc").
diagram_fact(fillColor, cell_31, "#d5e8d4").
diagram_fact(fillColor, cell_32, "#d5e8d4").
diagram_fact(fillColor, cell_40, "#dae8fc").
diagram_fact(fillColor, cell_42, "#fff2cc").
diagram_fact(fillColor, cell_43, "#dae8fc").
diagram_fact(fillColor, cell_44, "#d5e8d4").
diagram_fact(fillColor, cell_46, "#d5e8d4").
diagram_fact(fillColor, cell_47, "#d5e8d4").
diagram_fact(fillColor, cell_62, "#dae8fc").
diagram_fact(fillColor, cell_63, "#f8cecc").
diagram_fact(fillColor, cell_65, "#fff2cc").
diagram_fact(fillColor, cell_66, "#dae8fc").
diagram_fact(fillColor, cell_67, "#d5e8d4").
diagram_fact(fillColor, cell_68, "#f8cecc").
diagram_fact(fillColor, cell_7, "#dae8fc").
diagram_fact(fillColor, cell_70, "#d5e8d4").
diagram_fact(fillColor, cell_71, "#d5e8d4").
diagram_fact(fillColor, cell_8, "#f8cecc").
diagram_fact(fillColor, cell_87, "#dae8fc").
diagram_fact(fillColor, cell_88, "#f8cecc").
diagram_fact(fillColor, cell_90, "#fff2cc").
diagram_fact(fillColor, cell_91, "#dae8fc").
diagram_fact(fillColor, cell_92, "#d5e8d4").
diagram_fact(fillColor, cell_93, "#f8cecc").
diagram_fact(fillColor, cell_95, "#d5e8d4").
diagram_fact(fillColor, cell_96, "#d5e8d4").
diagram_fact(glass, cell_100, 0).
diagram_fact(glass, cell_101, 0).
diagram_fact(glass, cell_102, 0).
diagram_fact(glass, cell_103, 0).
diagram_fact(glass, cell_104, 0).
diagram_fact(glass, cell_105, 0).
diagram_fact(glass, cell_120, 0).
diagram_fact(glass, cell_121, 0).
diagram_fact(glass, cell_122, 0).
diagram_fact(glass, cell_123, 0).
diagram_fact(glass, cell_124, 0).
diagram_fact(glass, cell_33, 0).
diagram_fact(glass, cell_48, 0).
diagram_fact(glass, cell_49, 0).
diagram_fact(glass, cell_50, 0).
diagram_fact(glass, cell_51, 0).
diagram_fact(glass, cell_52, 0).
diagram_fact(glass, cell_53, 0).
diagram_fact(glass, cell_54, 0).
diagram_fact(glass, cell_55, 0).
diagram_fact(glass, cell_72, 0).
diagram_fact(glass, cell_73, 0).
diagram_fact(glass, cell_74, 0).
diagram_fact(glass, cell_75, 0).
diagram_fact(glass, cell_76, 0).
diagram_fact(glass, cell_77, 0).
diagram_fact(glass, cell_78, 0).
diagram_fact(glass, cell_79, 0).
diagram_fact(glass, cell_80, 0).
diagram_fact(glass, cell_97, 0).
diagram_fact(glass, cell_98, 0).
diagram_fact(glass, cell_99, 0).
diagram_fact(gradientColor, cell_11, "#7ea6e0").
diagram_fact(gradientColor, cell_112, "#7ea6e0").
diagram_fact(gradientColor, cell_115, "#7ea6e0").
diagram_fact(gradientColor, cell_23, "#7ea6e0").
diagram_fact(gradientColor, cell_27, "#7ea6e0").
diagram_fact(gradientColor, cell_40, "#7ea6e0").
diagram_fact(gradientColor, cell_43, "#7ea6e0").
diagram_fact(gradientColor, cell_62, "#7ea6e0").
diagram_fact(gradientColor, cell_66, "#7ea6e0").
diagram_fact(gradientColor, cell_7, "#7ea6e0").
diagram_fact(gradientColor, cell_87, "#7ea6e0").
diagram_fact(gradientColor, cell_91, "#7ea6e0").
diagram_fact(height, cell_10, 40).
diagram_fact(height, cell_100, 430).
diagram_fact(height, cell_101, 338.7,5).
diagram_fact(height, cell_102, 329.3,7).
diagram_fact(height, cell_103, 70).
diagram_fact(height, cell_104, 75).
diagram_fact(height, cell_105, 73.7,5).
diagram_fact(height, cell_11, 110).
diagram_fact(height, cell_111, 480).
diagram_fact(height, cell_112, 130).
diagram_fact(height, cell_114, 40).
diagram_fact(height, cell_115, 110).
diagram_fact(height, cell_116, 40).
diagram_fact(height, cell_118, 40).
diagram_fact(height, cell_119, 40).
diagram_fact(height, cell_12, 40).
diagram_fact(height, cell_120, 360).
diagram_fact(height, cell_121, 520).
diagram_fact(height, cell_122, 430).
diagram_fact(height, cell_123, 430).
diagram_fact(height, cell_124, 360).
diagram_fact(height, cell_13, 35).
diagram_fact(height, cell_15, 40).
diagram_fact(height, cell_16, 40).
diagram_fact(height, cell_22, 480).
diagram_fact(height, cell_23, 130).
diagram_fact(height, cell_24, 45).
diagram_fact(height, cell_26, 40).
diagram_fact(height, cell_27, 110).
diagram_fact(height, cell_28, 40).
diagram_fact(height, cell_29, 35).
diagram_fact(height, cell_31, 40).
diagram_fact(height, cell_32, 40).
diagram_fact(height, cell_33, 430).
diagram_fact(height, cell_39, 480).
diagram_fact(height, cell_40, 130).
diagram_fact(height, cell_42, 40).
diagram_fact(height, cell_43, 110).
diagram_fact(height, cell_44, 40).
diagram_fact(height, cell_46, 40).
diagram_fact(height, cell_47, 40).
diagram_fact(height, cell_48, 520).
diagram_fact(height, cell_49, 520).
diagram_fact(height, cell_50, 430).
diagram_fact(height, cell_51, 430).
diagram_fact(height, cell_52, 329.3,7).
diagram_fact(height, cell_53, 70).
diagram_fact(height, cell_54, 75).
diagram_fact(height, cell_55, 73.7,5).
diagram_fact(height, cell_6, 480).
diagram_fact(height, cell_61, 480).
diagram_fact(height, cell_62, 130).
diagram_fact(height, cell_63, 45).
diagram_fact(height, cell_65, 40).
diagram_fact(height, cell_66, 110).
diagram_fact(height, cell_67, 40).
diagram_fact(height, cell_68, 35).
diagram_fact(height, cell_7, 130).
diagram_fact(height, cell_70, 40).
diagram_fact(height, cell_71, 40).
diagram_fact(height, cell_72, 520).
diagram_fact(height, cell_73, 520).
diagram_fact(height, cell_74, 430).
diagram_fact(height, cell_75, 430).
diagram_fact(height, cell_76, 291.2,5).
diagram_fact(height, cell_77, 329.3,7).
diagram_fact(height, cell_78, 80).
diagram_fact(height, cell_79, 75).
diagram_fact(height, cell_8, 45).
diagram_fact(height, cell_80, 73.7,5).
diagram_fact(height, cell_86, 480).
diagram_fact(height, cell_87, 130).
diagram_fact(height, cell_88, 45).
diagram_fact(height, cell_90, 40).
diagram_fact(height, cell_91, 110).
diagram_fact(height, cell_92, 40).
diagram_fact(height, cell_93, 35).
diagram_fact(height, cell_95, 40).
diagram_fact(height, cell_96, 40).
diagram_fact(height, cell_97, 520).
diagram_fact(height, cell_98, 520).
diagram_fact(height, cell_99, 430).
diagram_fact(html, cell_10, 1).
diagram_fact(html, cell_100, 1).
diagram_fact(html, cell_101, 1).
diagram_fact(html, cell_102, 1).
diagram_fact(html, cell_103, 1).
diagram_fact(html, cell_104, 1).
diagram_fact(html, cell_105, 1).
diagram_fact(html, cell_11, 1).
diagram_fact(html, cell_111, 1).
diagram_fact(html, cell_112, 1).
diagram_fact(html, cell_113, 1).
diagram_fact(html, cell_114, 1).
diagram_fact(html, cell_115, 1).
diagram_fact(html, cell_116, 1).
diagram_fact(html, cell_117, 1).
diagram_fact(html, cell_118, 1).
diagram_fact(html, cell_119, 1).
diagram_fact(html, cell_12, 1).
diagram_fact(html, cell_120, 1).
diagram_fact(html, cell_121, 1).
diagram_fact(html, cell_122, 1).
diagram_fact(html, cell_123, 1).
diagram_fact(html, cell_124, 1).
diagram_fact(html, cell_13, 1).
diagram_fact(html, cell_14, 1).
diagram_fact(html, cell_15, 1).
diagram_fact(html, cell_16, 1).
diagram_fact(html, cell_22, 1).
diagram_fact(html, cell_23, 1).
diagram_fact(html, cell_24, 1).
diagram_fact(html, cell_25, 1).
diagram_fact(html, cell_26, 1).
diagram_fact(html, cell_27, 1).
diagram_fact(html, cell_28, 1).
diagram_fact(html, cell_29, 1).
diagram_fact(html, cell_30, 1).
diagram_fact(html, cell_31, 1).
diagram_fact(html, cell_32, 1).
diagram_fact(html, cell_33, 1).
diagram_fact(html, cell_39, 1).
diagram_fact(html, cell_40, 1).
diagram_fact(html, cell_41, 1).
diagram_fact(html, cell_42, 1).
diagram_fact(html, cell_43, 1).
diagram_fact(html, cell_44, 1).
diagram_fact(html, cell_45, 1).
diagram_fact(html, cell_46, 1).
diagram_fact(html, cell_47, 1).
diagram_fact(html, cell_48, 1).
diagram_fact(html, cell_49, 1).
diagram_fact(html, cell_50, 1).
diagram_fact(html, cell_51, 1).
diagram_fact(html, cell_52, 1).
diagram_fact(html, cell_53, 1).
diagram_fact(html, cell_54, 1).
diagram_fact(html, cell_55, 1).
diagram_fact(html, cell_6, 1).
diagram_fact(html, cell_61, 1).
diagram_fact(html, cell_62, 1).
diagram_fact(html, cell_63, 1).
diagram_fact(html, cell_64, 1).
diagram_fact(html, cell_65, 1).
diagram_fact(html, cell_66, 1).
diagram_fact(html, cell_67, 1).
diagram_fact(html, cell_68, 1).
diagram_fact(html, cell_69, 1).
diagram_fact(html, cell_7, 1).
diagram_fact(html, cell_70, 1).
diagram_fact(html, cell_71, 1).
diagram_fact(html, cell_72, 1).
diagram_fact(html, cell_73, 1).
diagram_fact(html, cell_74, 1).
diagram_fact(html, cell_75, 1).
diagram_fact(html, cell_76, 1).
diagram_fact(html, cell_77, 1).
diagram_fact(html, cell_78, 1).
diagram_fact(html, cell_79, 1).
diagram_fact(html, cell_8, 1).
diagram_fact(html, cell_80, 1).
diagram_fact(html, cell_86, 1).
diagram_fact(html, cell_87, 1).
diagram_fact(html, cell_88, 1).
diagram_fact(html, cell_89, 1).
diagram_fact(html, cell_9, 1).
diagram_fact(html, cell_90, 1).
diagram_fact(html, cell_91, 1).
diagram_fact(html, cell_92, 1).
diagram_fact(html, cell_93, 1).
diagram_fact(html, cell_94, 1).
diagram_fact(html, cell_95, 1).
diagram_fact(html, cell_96, 1).
diagram_fact(html, cell_97, 1).
diagram_fact(html, cell_98, 1).
diagram_fact(html, cell_99, 1).
diagram_fact(jettySize, cell_113, "auto").
diagram_fact(jettySize, cell_117, "auto").
diagram_fact(jettySize, cell_14, "auto").
diagram_fact(jettySize, cell_25, "auto").
diagram_fact(jettySize, cell_30, "auto").
diagram_fact(jettySize, cell_41, "auto").
diagram_fact(jettySize, cell_45, "auto").
diagram_fact(jettySize, cell_64, "auto").
diagram_fact(jettySize, cell_69, "auto").
diagram_fact(jettySize, cell_89, "auto").
diagram_fact(jettySize, cell_9, "auto").
diagram_fact(jettySize, cell_94, "auto").
diagram_fact(kind, cell_10, "ellipse").
diagram_fact(kind, cell_114, "ellipse").
diagram_fact(kind, cell_116, "ellipse").
diagram_fact(kind, cell_118, "ellipse").
diagram_fact(kind, cell_119, "ellipse").
diagram_fact(kind, cell_12, "ellipse").
diagram_fact(kind, cell_15, "ellipse").
diagram_fact(kind, cell_16, "ellipse").
diagram_fact(kind, cell_26, "ellipse").
diagram_fact(kind, cell_28, "ellipse").
diagram_fact(kind, cell_31, "ellipse").
diagram_fact(kind, cell_32, "ellipse").
diagram_fact(kind, cell_42, "ellipse").
diagram_fact(kind, cell_44, "ellipse").
diagram_fact(kind, cell_46, "ellipse").
diagram_fact(kind, cell_47, "ellipse").
diagram_fact(kind, cell_65, "ellipse").
diagram_fact(kind, cell_67, "ellipse").
diagram_fact(kind, cell_70, "ellipse").
diagram_fact(kind, cell_71, "ellipse").
diagram_fact(kind, cell_90, "ellipse").
diagram_fact(kind, cell_92, "ellipse").
diagram_fact(kind, cell_95, "ellipse").
diagram_fact(kind, cell_96, "ellipse").
diagram_fact(mxGraphModel, mxGraphModel_107, mxGraphModel_107).
diagram_fact(mxGraphModel, mxGraphModel_18, mxGraphModel_18).
diagram_fact(mxGraphModel, mxGraphModel_2, mxGraphModel_2).
diagram_fact(mxGraphModel, mxGraphModel_35, mxGraphModel_35).
diagram_fact(mxGraphModel, mxGraphModel_57, mxGraphModel_57).
diagram_fact(mxGraphModel, mxGraphModel_82, mxGraphModel_82).
diagram_fact(name, diagram_1, "helloworld").
diagram_fact(name, diagram_106, "Message Routing").
diagram_fact(name, diagram_17, "Top Level").
diagram_fact(name, diagram_34, "Two Components").
diagram_fact(name, diagram_56, "Inside Hello").
diagram_fact(name, diagram_81, "Inside World").
diagram_fact(opacity, cell_100, 80).
diagram_fact(opacity, cell_101, 80).
diagram_fact(opacity, cell_102, 80).
diagram_fact(opacity, cell_103, 80).
diagram_fact(opacity, cell_104, 80).
diagram_fact(opacity, cell_105, 80).
diagram_fact(opacity, cell_120, 80).
diagram_fact(opacity, cell_121, 80).
diagram_fact(opacity, cell_122, 80).
diagram_fact(opacity, cell_123, 80).
diagram_fact(opacity, cell_124, 80).
diagram_fact(opacity, cell_33, 80).
diagram_fact(opacity, cell_48, 80).
diagram_fact(opacity, cell_49, 80).
diagram_fact(opacity, cell_50, 80).
diagram_fact(opacity, cell_51, 80).
diagram_fact(opacity, cell_52, 80).
diagram_fact(opacity, cell_53, 80).
diagram_fact(opacity, cell_54, 80).
diagram_fact(opacity, cell_55, 80).
diagram_fact(opacity, cell_72, 80).
diagram_fact(opacity, cell_73, 80).
diagram_fact(opacity, cell_74, 80).
diagram_fact(opacity, cell_75, 80).
diagram_fact(opacity, cell_76, 80).
diagram_fact(opacity, cell_77, 80).
diagram_fact(opacity, cell_78, 80).
diagram_fact(opacity, cell_79, 80).
diagram_fact(opacity, cell_80, 80).
diagram_fact(opacity, cell_97, 80).
diagram_fact(opacity, cell_98, 80).
diagram_fact(opacity, cell_99, 80).
diagram_fact(orthogonalLoop, cell_113, 1).
diagram_fact(orthogonalLoop, cell_117, 1).
diagram_fact(orthogonalLoop, cell_14, 1).
diagram_fact(orthogonalLoop, cell_25, 1).
diagram_fact(orthogonalLoop, cell_30, 1).
diagram_fact(orthogonalLoop, cell_41, 1).
diagram_fact(orthogonalLoop, cell_45, 1).
diagram_fact(orthogonalLoop, cell_64, 1).
diagram_fact(orthogonalLoop, cell_69, 1).
diagram_fact(orthogonalLoop, cell_89, 1).
diagram_fact(orthogonalLoop, cell_9, 1).
diagram_fact(orthogonalLoop, cell_94, 1).
diagram_fact(parent, cell_10, id_1).
diagram_fact(parent, cell_100, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_101, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_102, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_103, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_104, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_105, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_11, id_1).
diagram_fact(parent, cell_110, kZNd__Wzdg_h0sN2qTSRM__0).
diagram_fact(parent, cell_111, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_112, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_113, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_114, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_115, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_116, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_117, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_118, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_119, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_12, id_1).
diagram_fact(parent, cell_120, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_121, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_122, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_123, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_124, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(parent, cell_13, id_1).
diagram_fact(parent, cell_14, id_1).
diagram_fact(parent, cell_15, id_1).
diagram_fact(parent, cell_16, id_1).
diagram_fact(parent, cell_21, id_Zu8V3P3_V4nKsUTMMlPR__0).
diagram_fact(parent, cell_22, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_23, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_24, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_25, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_26, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_27, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_28, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_29, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_30, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_31, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_32, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_33, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(parent, cell_38, id_KqhYrDwXJiJhXW4oFgyK__0).
diagram_fact(parent, cell_39, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_40, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_41, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_42, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_43, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_44, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_45, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_46, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_47, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_48, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_49, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_5, id_0).
diagram_fact(parent, cell_50, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_51, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_52, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_53, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_54, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_55, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(parent, cell_6, id_1).
diagram_fact(parent, cell_60, oUlXWID28vXoG6CZzVJF__0).
diagram_fact(parent, cell_61, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_62, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_63, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_64, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_65, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_66, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_67, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_68, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_69, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_7, id_1).
diagram_fact(parent, cell_70, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_71, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_72, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_73, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_74, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_75, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_76, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_77, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_78, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_79, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_8, id_1).
diagram_fact(parent, cell_80, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(parent, cell_85, id_HCTKjbojjSiwvVzEPJlV__0).
diagram_fact(parent, cell_86, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_87, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_88, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_89, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_9, id_1).
diagram_fact(parent, cell_90, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_91, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_92, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_93, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_94, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_95, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_96, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_97, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_98, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(parent, cell_99, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(relative, cell_113, 1).
diagram_fact(relative, cell_117, 1).
diagram_fact(relative, cell_14, 1).
diagram_fact(relative, cell_25, 1).
diagram_fact(relative, cell_30, 1).
diagram_fact(relative, cell_41, 1).
diagram_fact(relative, cell_45, 1).
diagram_fact(relative, cell_64, 1).
diagram_fact(relative, cell_69, 1).
diagram_fact(relative, cell_89, 1).
diagram_fact(relative, cell_9, 1).
diagram_fact(relative, cell_94, 1).
diagram_fact(root, root_108, root_108).
diagram_fact(root, root_19, root_19).
diagram_fact(root, root_3, root_3).
diagram_fact(root, root_36, root_36).
diagram_fact(root, root_58, root_58).
diagram_fact(root, root_83, root_83).
diagram_fact(rotation, cell_100, 90).
diagram_fact(rotation, cell_101, 90).
diagram_fact(rotation, cell_102, 90).
diagram_fact(rotation, cell_103, 90).
diagram_fact(rotation, cell_104, 90).
diagram_fact(rotation, cell_105, 90).
diagram_fact(rotation, cell_122, 90).
diagram_fact(rotation, cell_123, 90).
diagram_fact(rotation, cell_50, 90).
diagram_fact(rotation, cell_51, 90).
diagram_fact(rotation, cell_52, 90).
diagram_fact(rotation, cell_53, 90).
diagram_fact(rotation, cell_54, 90).
diagram_fact(rotation, cell_55, 90).
diagram_fact(rotation, cell_74, 90).
diagram_fact(rotation, cell_75, 90).
diagram_fact(rotation, cell_76, 90).
diagram_fact(rotation, cell_77, 90).
diagram_fact(rotation, cell_78, 90).
diagram_fact(rotation, cell_79, 90).
diagram_fact(rotation, cell_80, 90).
diagram_fact(rotation, cell_99, 90).
diagram_fact(rounded, cell_100, 1).
diagram_fact(rounded, cell_101, 1).
diagram_fact(rounded, cell_102, 1).
diagram_fact(rounded, cell_103, 1).
diagram_fact(rounded, cell_104, 1).
diagram_fact(rounded, cell_105, 1).
diagram_fact(rounded, cell_11, 1).
diagram_fact(rounded, cell_111, 1).
diagram_fact(rounded, cell_112, 1).
diagram_fact(rounded, cell_113, 0).
diagram_fact(rounded, cell_115, 1).
diagram_fact(rounded, cell_117, 0).
diagram_fact(rounded, cell_120, 1).
diagram_fact(rounded, cell_121, 1).
diagram_fact(rounded, cell_122, 1).
diagram_fact(rounded, cell_123, 1).
diagram_fact(rounded, cell_124, 1).
diagram_fact(rounded, cell_13, 0).
diagram_fact(rounded, cell_14, 0).
diagram_fact(rounded, cell_22, 1).
diagram_fact(rounded, cell_23, 1).
diagram_fact(rounded, cell_24, 0).
diagram_fact(rounded, cell_25, 0).
diagram_fact(rounded, cell_27, 1).
diagram_fact(rounded, cell_29, 0).
diagram_fact(rounded, cell_30, 0).
diagram_fact(rounded, cell_33, 1).
diagram_fact(rounded, cell_39, 1).
diagram_fact(rounded, cell_40, 1).
diagram_fact(rounded, cell_41, 0).
diagram_fact(rounded, cell_43, 1).
diagram_fact(rounded, cell_45, 0).
diagram_fact(rounded, cell_48, 1).
diagram_fact(rounded, cell_49, 1).
diagram_fact(rounded, cell_50, 1).
diagram_fact(rounded, cell_51, 1).
diagram_fact(rounded, cell_52, 1).
diagram_fact(rounded, cell_53, 1).
diagram_fact(rounded, cell_54, 1).
diagram_fact(rounded, cell_55, 1).
diagram_fact(rounded, cell_6, 1).
diagram_fact(rounded, cell_61, 1).
diagram_fact(rounded, cell_62, 1).
diagram_fact(rounded, cell_63, 0).
diagram_fact(rounded, cell_64, 0).
diagram_fact(rounded, cell_66, 1).
diagram_fact(rounded, cell_68, 0).
diagram_fact(rounded, cell_69, 0).
diagram_fact(rounded, cell_7, 1).
diagram_fact(rounded, cell_72, 1).
diagram_fact(rounded, cell_73, 1).
diagram_fact(rounded, cell_74, 1).
diagram_fact(rounded, cell_75, 1).
diagram_fact(rounded, cell_76, 1).
diagram_fact(rounded, cell_77, 1).
diagram_fact(rounded, cell_78, 1).
diagram_fact(rounded, cell_79, 1).
diagram_fact(rounded, cell_8, 0).
diagram_fact(rounded, cell_80, 1).
diagram_fact(rounded, cell_86, 1).
diagram_fact(rounded, cell_87, 1).
diagram_fact(rounded, cell_88, 0).
diagram_fact(rounded, cell_89, 0).
diagram_fact(rounded, cell_9, 0).
diagram_fact(rounded, cell_91, 1).
diagram_fact(rounded, cell_93, 0).
diagram_fact(rounded, cell_94, 0).
diagram_fact(rounded, cell_97, 1).
diagram_fact(rounded, cell_98, 1).
diagram_fact(rounded, cell_99, 1).
diagram_fact(sketch, cell_100, 0).
diagram_fact(sketch, cell_101, 0).
diagram_fact(sketch, cell_102, 0).
diagram_fact(sketch, cell_103, 0).
diagram_fact(sketch, cell_104, 0).
diagram_fact(sketch, cell_105, 0).
diagram_fact(sketch, cell_120, 0).
diagram_fact(sketch, cell_121, 0).
diagram_fact(sketch, cell_122, 0).
diagram_fact(sketch, cell_123, 0).
diagram_fact(sketch, cell_124, 0).
diagram_fact(sketch, cell_33, 0).
diagram_fact(sketch, cell_48, 0).
diagram_fact(sketch, cell_49, 0).
diagram_fact(sketch, cell_50, 0).
diagram_fact(sketch, cell_51, 0).
diagram_fact(sketch, cell_52, 0).
diagram_fact(sketch, cell_53, 0).
diagram_fact(sketch, cell_54, 0).
diagram_fact(sketch, cell_55, 0).
diagram_fact(sketch, cell_72, 0).
diagram_fact(sketch, cell_73, 0).
diagram_fact(sketch, cell_74, 0).
diagram_fact(sketch, cell_75, 0).
diagram_fact(sketch, cell_76, 0).
diagram_fact(sketch, cell_77, 0).
diagram_fact(sketch, cell_78, 0).
diagram_fact(sketch, cell_79, 0).
diagram_fact(sketch, cell_80, 0).
diagram_fact(sketch, cell_97, 0).
diagram_fact(sketch, cell_98, 0).
diagram_fact(sketch, cell_99, 0).
diagram_fact(source, cell_113, kZNd__Wzdg_h0sN2qTSRM__6).
diagram_fact(source, cell_117, kZNd__Wzdg_h0sN2qTSRM__11).
diagram_fact(source, cell_14, id_Eg2JflB1LH7_nM4HlBUV__1).
diagram_fact(source, cell_25, id_Zu8V3P3_V4nKsUTMMlPR__6).
diagram_fact(source, cell_30, id_Zu8V3P3_V4nKsUTMMlPR__11).
diagram_fact(source, cell_41, id_KqhYrDwXJiJhXW4oFgyK__6).
diagram_fact(source, cell_45, id_KqhYrDwXJiJhXW4oFgyK__11).
diagram_fact(source, cell_64, oUlXWID28vXoG6CZzVJF__6).
diagram_fact(source, cell_69, oUlXWID28vXoG6CZzVJF__11).
diagram_fact(source, cell_89, id_HCTKjbojjSiwvVzEPJlV__6).
diagram_fact(source, cell_9, i5jZ3dy8F4nkPbaXPHF6__5).
diagram_fact(source, cell_94, id_HCTKjbojjSiwvVzEPJlV__11).
diagram_fact(strokeColor, cell_10, "#d6b656").
diagram_fact(strokeColor, cell_100, "none").
diagram_fact(strokeColor, cell_101, "none").
diagram_fact(strokeColor, cell_102, "none").
diagram_fact(strokeColor, cell_103, "none").
diagram_fact(strokeColor, cell_104, "none").
diagram_fact(strokeColor, cell_105, "none").
diagram_fact(strokeColor, cell_11, "#6c8ebf").
diagram_fact(strokeColor, cell_112, "#6c8ebf").
diagram_fact(strokeColor, cell_114, "#d6b656").
diagram_fact(strokeColor, cell_115, "#6c8ebf").
diagram_fact(strokeColor, cell_116, "#82b366").
diagram_fact(strokeColor, cell_118, "#82b366").
diagram_fact(strokeColor, cell_119, "#82b366").
diagram_fact(strokeColor, cell_12, "#82b366").
diagram_fact(strokeColor, cell_120, "none").
diagram_fact(strokeColor, cell_121, "none").
diagram_fact(strokeColor, cell_122, "none").
diagram_fact(strokeColor, cell_123, "none").
diagram_fact(strokeColor, cell_124, "none").
diagram_fact(strokeColor, cell_13, "#b85450").
diagram_fact(strokeColor, cell_15, "#82b366").
diagram_fact(strokeColor, cell_16, "#82b366").
diagram_fact(strokeColor, cell_23, "#6c8ebf").
diagram_fact(strokeColor, cell_24, "#b85450").
diagram_fact(strokeColor, cell_26, "#d6b656").
diagram_fact(strokeColor, cell_27, "#6c8ebf").
diagram_fact(strokeColor, cell_28, "#82b366").
diagram_fact(strokeColor, cell_29, "#b85450").
diagram_fact(strokeColor, cell_31, "#82b366").
diagram_fact(strokeColor, cell_32, "#82b366").
diagram_fact(strokeColor, cell_33, "none").
diagram_fact(strokeColor, cell_40, "#6c8ebf").
diagram_fact(strokeColor, cell_42, "#d6b656").
diagram_fact(strokeColor, cell_43, "#6c8ebf").
diagram_fact(strokeColor, cell_44, "#82b366").
diagram_fact(strokeColor, cell_46, "#82b366").
diagram_fact(strokeColor, cell_47, "#82b366").
diagram_fact(strokeColor, cell_48, "none").
diagram_fact(strokeColor, cell_49, "none").
diagram_fact(strokeColor, cell_50, "none").
diagram_fact(strokeColor, cell_51, "none").
diagram_fact(strokeColor, cell_52, "none").
diagram_fact(strokeColor, cell_53, "none").
diagram_fact(strokeColor, cell_54, "none").
diagram_fact(strokeColor, cell_55, "none").
diagram_fact(strokeColor, cell_62, "#6c8ebf").
diagram_fact(strokeColor, cell_63, "#b85450").
diagram_fact(strokeColor, cell_65, "#d6b656").
diagram_fact(strokeColor, cell_66, "#6c8ebf").
diagram_fact(strokeColor, cell_67, "#82b366").
diagram_fact(strokeColor, cell_68, "#b85450").
diagram_fact(strokeColor, cell_7, "#6c8ebf").
diagram_fact(strokeColor, cell_70, "#82b366").
diagram_fact(strokeColor, cell_71, "#82b366").
diagram_fact(strokeColor, cell_72, "none").
diagram_fact(strokeColor, cell_73, "none").
diagram_fact(strokeColor, cell_74, "none").
diagram_fact(strokeColor, cell_75, "none").
diagram_fact(strokeColor, cell_76, "none").
diagram_fact(strokeColor, cell_77, "none").
diagram_fact(strokeColor, cell_78, "none").
diagram_fact(strokeColor, cell_79, "none").
diagram_fact(strokeColor, cell_8, "#b85450").
diagram_fact(strokeColor, cell_80, "none").
diagram_fact(strokeColor, cell_87, "#6c8ebf").
diagram_fact(strokeColor, cell_88, "#b85450").
diagram_fact(strokeColor, cell_90, "#d6b656").
diagram_fact(strokeColor, cell_91, "#6c8ebf").
diagram_fact(strokeColor, cell_92, "#82b366").
diagram_fact(strokeColor, cell_93, "#b85450").
diagram_fact(strokeColor, cell_95, "#82b366").
diagram_fact(strokeColor, cell_96, "#82b366").
diagram_fact(strokeColor, cell_97, "none").
diagram_fact(strokeColor, cell_98, "none").
diagram_fact(strokeColor, cell_99, "none").
diagram_fact(synonym, cell_10, i5jZ3dy8F4nkPbaXPHF6__5).
diagram_fact(synonym, cell_100, id_HCTKjbojjSiwvVzEPJlV__16).
diagram_fact(synonym, cell_101, id_HCTKjbojjSiwvVzEPJlV__18).
diagram_fact(synonym, cell_102, id_HCTKjbojjSiwvVzEPJlV__19).
diagram_fact(synonym, cell_103, id_HCTKjbojjSiwvVzEPJlV__20).
diagram_fact(synonym, cell_104, id_HCTKjbojjSiwvVzEPJlV__21).
diagram_fact(synonym, cell_105, id_HCTKjbojjSiwvVzEPJlV__22).
diagram_fact(synonym, cell_109, kZNd__Wzdg_h0sN2qTSRM__0).
diagram_fact(synonym, cell_11, i5jZ3dy8F4nkPbaXPHF6__6).
diagram_fact(synonym, cell_110, kZNd__Wzdg_h0sN2qTSRM__1).
diagram_fact(synonym, cell_111, kZNd__Wzdg_h0sN2qTSRM__2).
diagram_fact(synonym, cell_112, kZNd__Wzdg_h0sN2qTSRM__3).
diagram_fact(synonym, cell_113, kZNd__Wzdg_h0sN2qTSRM__5).
diagram_fact(synonym, cell_114, kZNd__Wzdg_h0sN2qTSRM__6).
diagram_fact(synonym, cell_115, kZNd__Wzdg_h0sN2qTSRM__7).
diagram_fact(synonym, cell_116, kZNd__Wzdg_h0sN2qTSRM__8).
diagram_fact(synonym, cell_117, kZNd__Wzdg_h0sN2qTSRM__10).
diagram_fact(synonym, cell_118, kZNd__Wzdg_h0sN2qTSRM__11).
diagram_fact(synonym, cell_119, kZNd__Wzdg_h0sN2qTSRM__12).
diagram_fact(synonym, cell_12, i5jZ3dy8F4nkPbaXPHF6__9).
diagram_fact(synonym, cell_120, kZNd__Wzdg_h0sN2qTSRM__13).
diagram_fact(synonym, cell_121, kZNd__Wzdg_h0sN2qTSRM__14).
diagram_fact(synonym, cell_122, kZNd__Wzdg_h0sN2qTSRM__15).
diagram_fact(synonym, cell_123, kZNd__Wzdg_h0sN2qTSRM__16).
diagram_fact(synonym, cell_124, kZNd__Wzdg_h0sN2qTSRM__19).
diagram_fact(synonym, cell_13, id_5xomNgWtBKOTZXKJYYDN__1).
diagram_fact(synonym, cell_14, id_Eg2JflB1LH7_nM4HlBUV__3).
diagram_fact(synonym, cell_15, id_Eg2JflB1LH7_nM4HlBUV__1).
diagram_fact(synonym, cell_16, id_Eg2JflB1LH7_nM4HlBUV__2).
diagram_fact(synonym, cell_20, id_Zu8V3P3_V4nKsUTMMlPR__0).
diagram_fact(synonym, cell_21, id_Zu8V3P3_V4nKsUTMMlPR__1).
diagram_fact(synonym, cell_22, id_Zu8V3P3_V4nKsUTMMlPR__2).
diagram_fact(synonym, cell_23, id_Zu8V3P3_V4nKsUTMMlPR__3).
diagram_fact(synonym, cell_24, id_Zu8V3P3_V4nKsUTMMlPR__4).
diagram_fact(synonym, cell_25, id_Zu8V3P3_V4nKsUTMMlPR__5).
diagram_fact(synonym, cell_26, id_Zu8V3P3_V4nKsUTMMlPR__6).
diagram_fact(synonym, cell_27, id_Zu8V3P3_V4nKsUTMMlPR__7).
diagram_fact(synonym, cell_28, id_Zu8V3P3_V4nKsUTMMlPR__8).
diagram_fact(synonym, cell_29, id_Zu8V3P3_V4nKsUTMMlPR__9).
diagram_fact(synonym, cell_30, id_Zu8V3P3_V4nKsUTMMlPR__10).
diagram_fact(synonym, cell_31, id_Zu8V3P3_V4nKsUTMMlPR__11).
diagram_fact(synonym, cell_32, id_Zu8V3P3_V4nKsUTMMlPR__12).
diagram_fact(synonym, cell_33, id_Zu8V3P3_V4nKsUTMMlPR__13).
diagram_fact(synonym, cell_37, id_KqhYrDwXJiJhXW4oFgyK__0).
diagram_fact(synonym, cell_38, id_KqhYrDwXJiJhXW4oFgyK__1).
diagram_fact(synonym, cell_39, id_KqhYrDwXJiJhXW4oFgyK__2).
diagram_fact(synonym, cell_4, id_0).
diagram_fact(synonym, cell_40, id_KqhYrDwXJiJhXW4oFgyK__3).
diagram_fact(synonym, cell_41, id_KqhYrDwXJiJhXW4oFgyK__5).
diagram_fact(synonym, cell_42, id_KqhYrDwXJiJhXW4oFgyK__6).
diagram_fact(synonym, cell_43, id_KqhYrDwXJiJhXW4oFgyK__7).
diagram_fact(synonym, cell_44, id_KqhYrDwXJiJhXW4oFgyK__8).
diagram_fact(synonym, cell_45, id_KqhYrDwXJiJhXW4oFgyK__10).
diagram_fact(synonym, cell_46, id_KqhYrDwXJiJhXW4oFgyK__11).
diagram_fact(synonym, cell_47, id_KqhYrDwXJiJhXW4oFgyK__12).
diagram_fact(synonym, cell_48, id_KqhYrDwXJiJhXW4oFgyK__13).
diagram_fact(synonym, cell_49, id_KqhYrDwXJiJhXW4oFgyK__14).
diagram_fact(synonym, cell_5, id_1).
diagram_fact(synonym, cell_50, id_KqhYrDwXJiJhXW4oFgyK__15).
diagram_fact(synonym, cell_51, id_KqhYrDwXJiJhXW4oFgyK__16).
diagram_fact(synonym, cell_52, id_KqhYrDwXJiJhXW4oFgyK__19).
diagram_fact(synonym, cell_53, id_KqhYrDwXJiJhXW4oFgyK__20).
diagram_fact(synonym, cell_54, id_KqhYrDwXJiJhXW4oFgyK__21).
diagram_fact(synonym, cell_55, id_KqhYrDwXJiJhXW4oFgyK__22).
diagram_fact(synonym, cell_59, oUlXWID28vXoG6CZzVJF__0).
diagram_fact(synonym, cell_6, i5jZ3dy8F4nkPbaXPHF6__1).
diagram_fact(synonym, cell_60, oUlXWID28vXoG6CZzVJF__1).
diagram_fact(synonym, cell_61, oUlXWID28vXoG6CZzVJF__2).
diagram_fact(synonym, cell_62, oUlXWID28vXoG6CZzVJF__3).
diagram_fact(synonym, cell_63, oUlXWID28vXoG6CZzVJF__4).
diagram_fact(synonym, cell_64, oUlXWID28vXoG6CZzVJF__5).
diagram_fact(synonym, cell_65, oUlXWID28vXoG6CZzVJF__6).
diagram_fact(synonym, cell_66, oUlXWID28vXoG6CZzVJF__7).
diagram_fact(synonym, cell_67, oUlXWID28vXoG6CZzVJF__8).
diagram_fact(synonym, cell_68, oUlXWID28vXoG6CZzVJF__9).
diagram_fact(synonym, cell_69, oUlXWID28vXoG6CZzVJF__10).
diagram_fact(synonym, cell_7, i5jZ3dy8F4nkPbaXPHF6__2).
diagram_fact(synonym, cell_70, oUlXWID28vXoG6CZzVJF__11).
diagram_fact(synonym, cell_71, oUlXWID28vXoG6CZzVJF__12).
diagram_fact(synonym, cell_72, oUlXWID28vXoG6CZzVJF__13).
diagram_fact(synonym, cell_73, oUlXWID28vXoG6CZzVJF__14).
diagram_fact(synonym, cell_74, oUlXWID28vXoG6CZzVJF__15).
diagram_fact(synonym, cell_75, oUlXWID28vXoG6CZzVJF__16).
diagram_fact(synonym, cell_76, oUlXWID28vXoG6CZzVJF__17).
diagram_fact(synonym, cell_77, oUlXWID28vXoG6CZzVJF__19).
diagram_fact(synonym, cell_78, oUlXWID28vXoG6CZzVJF__20).
diagram_fact(synonym, cell_79, oUlXWID28vXoG6CZzVJF__21).
diagram_fact(synonym, cell_8, i5jZ3dy8F4nkPbaXPHF6__3).
diagram_fact(synonym, cell_80, oUlXWID28vXoG6CZzVJF__22).
diagram_fact(synonym, cell_84, id_HCTKjbojjSiwvVzEPJlV__0).
diagram_fact(synonym, cell_85, id_HCTKjbojjSiwvVzEPJlV__1).
diagram_fact(synonym, cell_86, id_HCTKjbojjSiwvVzEPJlV__2).
diagram_fact(synonym, cell_87, id_HCTKjbojjSiwvVzEPJlV__3).
diagram_fact(synonym, cell_88, id_HCTKjbojjSiwvVzEPJlV__4).
diagram_fact(synonym, cell_89, id_HCTKjbojjSiwvVzEPJlV__5).
diagram_fact(synonym, cell_9, i5jZ3dy8F4nkPbaXPHF6__4).
diagram_fact(synonym, cell_90, id_HCTKjbojjSiwvVzEPJlV__6).
diagram_fact(synonym, cell_91, id_HCTKjbojjSiwvVzEPJlV__7).
diagram_fact(synonym, cell_92, id_HCTKjbojjSiwvVzEPJlV__8).
diagram_fact(synonym, cell_93, id_HCTKjbojjSiwvVzEPJlV__9).
diagram_fact(synonym, cell_94, id_HCTKjbojjSiwvVzEPJlV__10).
diagram_fact(synonym, cell_95, id_HCTKjbojjSiwvVzEPJlV__11).
diagram_fact(synonym, cell_96, id_HCTKjbojjSiwvVzEPJlV__12).
diagram_fact(synonym, cell_97, id_HCTKjbojjSiwvVzEPJlV__13).
diagram_fact(synonym, cell_98, id_HCTKjbojjSiwvVzEPJlV__14).
diagram_fact(synonym, cell_99, id_HCTKjbojjSiwvVzEPJlV__15).
diagram_fact(target, cell_113, kZNd__Wzdg_h0sN2qTSRM__8).
diagram_fact(target, cell_117, kZNd__Wzdg_h0sN2qTSRM__12).
diagram_fact(target, cell_14, id_Eg2JflB1LH7_nM4HlBUV__2).
diagram_fact(target, cell_25, id_Zu8V3P3_V4nKsUTMMlPR__8).
diagram_fact(target, cell_30, id_Zu8V3P3_V4nKsUTMMlPR__12).
diagram_fact(target, cell_41, id_KqhYrDwXJiJhXW4oFgyK__8).
diagram_fact(target, cell_45, id_KqhYrDwXJiJhXW4oFgyK__12).
diagram_fact(target, cell_64, oUlXWID28vXoG6CZzVJF__8).
diagram_fact(target, cell_69, oUlXWID28vXoG6CZzVJF__12).
diagram_fact(target, cell_89, id_HCTKjbojjSiwvVzEPJlV__8).
diagram_fact(target, cell_9, i5jZ3dy8F4nkPbaXPHF6__9).
diagram_fact(target, cell_94, id_HCTKjbojjSiwvVzEPJlV__12).
diagram_fact(value, cell_10, "out").
diagram_fact(value, cell_100, "").
diagram_fact(value, cell_101, "").
diagram_fact(value, cell_102, "").
diagram_fact(value, cell_103, "").
diagram_fact(value, cell_104, "").
diagram_fact(value, cell_105, "").
diagram_fact(value, cell_11, "world").
diagram_fact(value, cell_111, "helloworld").
diagram_fact(value, cell_112, "hello").
diagram_fact(value, cell_114, "out").
diagram_fact(value, cell_115, "world").
diagram_fact(value, cell_116, "in").
diagram_fact(value, cell_118, "go").
diagram_fact(value, cell_119, "a").
diagram_fact(value, cell_12, "in").
diagram_fact(value, cell_120, "").
diagram_fact(value, cell_121, "").
diagram_fact(value, cell_122, "").
diagram_fact(value, cell_123, "").
diagram_fact(value, cell_124, "").
diagram_fact(value, cell_13, "print (&quot;world&quot;)&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_15, "go").
diagram_fact(value, cell_16, "a").
diagram_fact(value, cell_22, "helloworld").
diagram_fact(value, cell_23, "hello").
diagram_fact(value, cell_24, "print (&quot;hello&quot;)&lt;br&gt;self.send (&quot;out&quot;, True)&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_26, "out").
diagram_fact(value, cell_27, "world").
diagram_fact(value, cell_28, "in").
diagram_fact(value, cell_29, "print (&quot;world&quot;)&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_31, "go").
diagram_fact(value, cell_32, "a").
diagram_fact(value, cell_33, "").
diagram_fact(value, cell_39, "helloworld").
diagram_fact(value, cell_40, "hello").
diagram_fact(value, cell_42, "out").
diagram_fact(value, cell_43, "world").
diagram_fact(value, cell_44, "in").
diagram_fact(value, cell_46, "go").
diagram_fact(value, cell_47, "a").
diagram_fact(value, cell_48, "").
diagram_fact(value, cell_49, "").
diagram_fact(value, cell_50, "").
diagram_fact(value, cell_51, "").
diagram_fact(value, cell_52, "").
diagram_fact(value, cell_53, "").
diagram_fact(value, cell_54, "").
diagram_fact(value, cell_55, "").
diagram_fact(value, cell_6, "helloworld").
diagram_fact(value, cell_61, "helloworld").
diagram_fact(value, cell_62, "hello").
diagram_fact(value, cell_63, "print (&quot;hello&quot;)&lt;br&gt;self.send (&quot;out&quot;, True)&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_65, "out").
diagram_fact(value, cell_66, "world").
diagram_fact(value, cell_67, "in").
diagram_fact(value, cell_68, "print (&quot;world&quot;)&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_7, "hello").
diagram_fact(value, cell_70, "go").
diagram_fact(value, cell_71, "a").
diagram_fact(value, cell_72, "").
diagram_fact(value, cell_73, "").
diagram_fact(value, cell_74, "").
diagram_fact(value, cell_75, "").
diagram_fact(value, cell_76, "").
diagram_fact(value, cell_77, "").
diagram_fact(value, cell_78, "").
diagram_fact(value, cell_79, "").
diagram_fact(value, cell_8, "print (&quot;hello&quot;)&lt;br&gt;self.send (&quot;out&quot;, True)&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_80, "").
diagram_fact(value, cell_86, "helloworld").
diagram_fact(value, cell_87, "hello").
diagram_fact(value, cell_88, "print (&quot;hello&quot;)&lt;br&gt;self.send (&quot;out&quot;, True)&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_90, "out").
diagram_fact(value, cell_91, "world").
diagram_fact(value, cell_92, "in").
diagram_fact(value, cell_93, "print (&quot;world&quot;)&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_95, "go").
diagram_fact(value, cell_96, "a").
diagram_fact(value, cell_97, "").
diagram_fact(value, cell_98, "").
diagram_fact(value, cell_99, "").
diagram_fact(vertex, cell_10, 1).
diagram_fact(vertex, cell_100, 1).
diagram_fact(vertex, cell_101, 1).
diagram_fact(vertex, cell_102, 1).
diagram_fact(vertex, cell_103, 1).
diagram_fact(vertex, cell_104, 1).
diagram_fact(vertex, cell_105, 1).
diagram_fact(vertex, cell_11, 1).
diagram_fact(vertex, cell_111, 1).
diagram_fact(vertex, cell_112, 1).
diagram_fact(vertex, cell_114, 1).
diagram_fact(vertex, cell_115, 1).
diagram_fact(vertex, cell_116, 1).
diagram_fact(vertex, cell_118, 1).
diagram_fact(vertex, cell_119, 1).
diagram_fact(vertex, cell_12, 1).
diagram_fact(vertex, cell_120, 1).
diagram_fact(vertex, cell_121, 1).
diagram_fact(vertex, cell_122, 1).
diagram_fact(vertex, cell_123, 1).
diagram_fact(vertex, cell_124, 1).
diagram_fact(vertex, cell_13, 1).
diagram_fact(vertex, cell_15, 1).
diagram_fact(vertex, cell_16, 1).
diagram_fact(vertex, cell_22, 1).
diagram_fact(vertex, cell_23, 1).
diagram_fact(vertex, cell_24, 1).
diagram_fact(vertex, cell_26, 1).
diagram_fact(vertex, cell_27, 1).
diagram_fact(vertex, cell_28, 1).
diagram_fact(vertex, cell_29, 1).
diagram_fact(vertex, cell_31, 1).
diagram_fact(vertex, cell_32, 1).
diagram_fact(vertex, cell_33, 1).
diagram_fact(vertex, cell_39, 1).
diagram_fact(vertex, cell_40, 1).
diagram_fact(vertex, cell_42, 1).
diagram_fact(vertex, cell_43, 1).
diagram_fact(vertex, cell_44, 1).
diagram_fact(vertex, cell_46, 1).
diagram_fact(vertex, cell_47, 1).
diagram_fact(vertex, cell_48, 1).
diagram_fact(vertex, cell_49, 1).
diagram_fact(vertex, cell_50, 1).
diagram_fact(vertex, cell_51, 1).
diagram_fact(vertex, cell_52, 1).
diagram_fact(vertex, cell_53, 1).
diagram_fact(vertex, cell_54, 1).
diagram_fact(vertex, cell_55, 1).
diagram_fact(vertex, cell_6, 1).
diagram_fact(vertex, cell_61, 1).
diagram_fact(vertex, cell_62, 1).
diagram_fact(vertex, cell_63, 1).
diagram_fact(vertex, cell_65, 1).
diagram_fact(vertex, cell_66, 1).
diagram_fact(vertex, cell_67, 1).
diagram_fact(vertex, cell_68, 1).
diagram_fact(vertex, cell_7, 1).
diagram_fact(vertex, cell_70, 1).
diagram_fact(vertex, cell_71, 1).
diagram_fact(vertex, cell_72, 1).
diagram_fact(vertex, cell_73, 1).
diagram_fact(vertex, cell_74, 1).
diagram_fact(vertex, cell_75, 1).
diagram_fact(vertex, cell_76, 1).
diagram_fact(vertex, cell_77, 1).
diagram_fact(vertex, cell_78, 1).
diagram_fact(vertex, cell_79, 1).
diagram_fact(vertex, cell_8, 1).
diagram_fact(vertex, cell_80, 1).
diagram_fact(vertex, cell_86, 1).
diagram_fact(vertex, cell_87, 1).
diagram_fact(vertex, cell_88, 1).
diagram_fact(vertex, cell_90, 1).
diagram_fact(vertex, cell_91, 1).
diagram_fact(vertex, cell_92, 1).
diagram_fact(vertex, cell_93, 1).
diagram_fact(vertex, cell_95, 1).
diagram_fact(vertex, cell_96, 1).
diagram_fact(vertex, cell_97, 1).
diagram_fact(vertex, cell_98, 1).
diagram_fact(vertex, cell_99, 1).
diagram_fact(verticalAlign, cell_11, "top").
diagram_fact(verticalAlign, cell_111, "top").
diagram_fact(verticalAlign, cell_112, "top").
diagram_fact(verticalAlign, cell_115, "top").
diagram_fact(verticalAlign, cell_22, "top").
diagram_fact(verticalAlign, cell_23, "top").
diagram_fact(verticalAlign, cell_27, "top").
diagram_fact(verticalAlign, cell_39, "top").
diagram_fact(verticalAlign, cell_40, "top").
diagram_fact(verticalAlign, cell_43, "top").
diagram_fact(verticalAlign, cell_6, "top").
diagram_fact(verticalAlign, cell_61, "top").
diagram_fact(verticalAlign, cell_62, "top").
diagram_fact(verticalAlign, cell_66, "top").
diagram_fact(verticalAlign, cell_7, "top").
diagram_fact(verticalAlign, cell_86, "top").
diagram_fact(verticalAlign, cell_87, "top").
diagram_fact(verticalAlign, cell_91, "top").
diagram_fact(whiteSpace, cell_10, "wrap").
diagram_fact(whiteSpace, cell_100, "wrap").
diagram_fact(whiteSpace, cell_101, "wrap").
diagram_fact(whiteSpace, cell_102, "wrap").
diagram_fact(whiteSpace, cell_103, "wrap").
diagram_fact(whiteSpace, cell_104, "wrap").
diagram_fact(whiteSpace, cell_105, "wrap").
diagram_fact(whiteSpace, cell_11, "wrap").
diagram_fact(whiteSpace, cell_111, "wrap").
diagram_fact(whiteSpace, cell_112, "wrap").
diagram_fact(whiteSpace, cell_114, "wrap").
diagram_fact(whiteSpace, cell_115, "wrap").
diagram_fact(whiteSpace, cell_116, "wrap").
diagram_fact(whiteSpace, cell_118, "wrap").
diagram_fact(whiteSpace, cell_119, "wrap").
diagram_fact(whiteSpace, cell_12, "wrap").
diagram_fact(whiteSpace, cell_120, "wrap").
diagram_fact(whiteSpace, cell_121, "wrap").
diagram_fact(whiteSpace, cell_122, "wrap").
diagram_fact(whiteSpace, cell_123, "wrap").
diagram_fact(whiteSpace, cell_124, "wrap").
diagram_fact(whiteSpace, cell_13, "wrap").
diagram_fact(whiteSpace, cell_15, "wrap").
diagram_fact(whiteSpace, cell_16, "wrap").
diagram_fact(whiteSpace, cell_22, "wrap").
diagram_fact(whiteSpace, cell_23, "wrap").
diagram_fact(whiteSpace, cell_24, "wrap").
diagram_fact(whiteSpace, cell_26, "wrap").
diagram_fact(whiteSpace, cell_27, "wrap").
diagram_fact(whiteSpace, cell_28, "wrap").
diagram_fact(whiteSpace, cell_29, "wrap").
diagram_fact(whiteSpace, cell_31, "wrap").
diagram_fact(whiteSpace, cell_32, "wrap").
diagram_fact(whiteSpace, cell_33, "wrap").
diagram_fact(whiteSpace, cell_39, "wrap").
diagram_fact(whiteSpace, cell_40, "wrap").
diagram_fact(whiteSpace, cell_42, "wrap").
diagram_fact(whiteSpace, cell_43, "wrap").
diagram_fact(whiteSpace, cell_44, "wrap").
diagram_fact(whiteSpace, cell_46, "wrap").
diagram_fact(whiteSpace, cell_47, "wrap").
diagram_fact(whiteSpace, cell_48, "wrap").
diagram_fact(whiteSpace, cell_49, "wrap").
diagram_fact(whiteSpace, cell_50, "wrap").
diagram_fact(whiteSpace, cell_51, "wrap").
diagram_fact(whiteSpace, cell_52, "wrap").
diagram_fact(whiteSpace, cell_53, "wrap").
diagram_fact(whiteSpace, cell_54, "wrap").
diagram_fact(whiteSpace, cell_55, "wrap").
diagram_fact(whiteSpace, cell_6, "wrap").
diagram_fact(whiteSpace, cell_61, "wrap").
diagram_fact(whiteSpace, cell_62, "wrap").
diagram_fact(whiteSpace, cell_63, "wrap").
diagram_fact(whiteSpace, cell_65, "wrap").
diagram_fact(whiteSpace, cell_66, "wrap").
diagram_fact(whiteSpace, cell_67, "wrap").
diagram_fact(whiteSpace, cell_68, "wrap").
diagram_fact(whiteSpace, cell_7, "wrap").
diagram_fact(whiteSpace, cell_70, "wrap").
diagram_fact(whiteSpace, cell_71, "wrap").
diagram_fact(whiteSpace, cell_72, "wrap").
diagram_fact(whiteSpace, cell_73, "wrap").
diagram_fact(whiteSpace, cell_74, "wrap").
diagram_fact(whiteSpace, cell_75, "wrap").
diagram_fact(whiteSpace, cell_76, "wrap").
diagram_fact(whiteSpace, cell_77, "wrap").
diagram_fact(whiteSpace, cell_78, "wrap").
diagram_fact(whiteSpace, cell_79, "wrap").
diagram_fact(whiteSpace, cell_8, "wrap").
diagram_fact(whiteSpace, cell_80, "wrap").
diagram_fact(whiteSpace, cell_86, "wrap").
diagram_fact(whiteSpace, cell_87, "wrap").
diagram_fact(whiteSpace, cell_88, "wrap").
diagram_fact(whiteSpace, cell_90, "wrap").
diagram_fact(whiteSpace, cell_91, "wrap").
diagram_fact(whiteSpace, cell_92, "wrap").
diagram_fact(whiteSpace, cell_93, "wrap").
diagram_fact(whiteSpace, cell_95, "wrap").
diagram_fact(whiteSpace, cell_96, "wrap").
diagram_fact(whiteSpace, cell_97, "wrap").
diagram_fact(whiteSpace, cell_98, "wrap").
diagram_fact(whiteSpace, cell_99, "wrap").
diagram_fact(width, cell_10, 40).
diagram_fact(width, cell_100, 90).
diagram_fact(width, cell_101, 160).
diagram_fact(width, cell_102, 79.6,9).
diagram_fact(width, cell_103, 80.6,3).
diagram_fact(width, cell_104, 112.5).
diagram_fact(width, cell_105, 112.5).
diagram_fact(width, cell_11, 265).
diagram_fact(width, cell_111, 510).
diagram_fact(width, cell_112, 260).
diagram_fact(width, cell_114, 40).
diagram_fact(width, cell_115, 265).
diagram_fact(width, cell_116, 40).
diagram_fact(width, cell_118, 40).
diagram_fact(width, cell_119, 40).
diagram_fact(width, cell_12, 40).
diagram_fact(width, cell_120, 90).
diagram_fact(width, cell_121, 90).
diagram_fact(width, cell_122, 90).
diagram_fact(width, cell_123, 90).
diagram_fact(width, cell_124, 90).
diagram_fact(width, cell_13, 220).
diagram_fact(width, cell_15, 40).
diagram_fact(width, cell_16, 40).
diagram_fact(width, cell_22, 510).
diagram_fact(width, cell_23, 260).
diagram_fact(width, cell_24, 200).
diagram_fact(width, cell_26, 40).
diagram_fact(width, cell_27, 265).
diagram_fact(width, cell_28, 40).
diagram_fact(width, cell_29, 220).
diagram_fact(width, cell_31, 40).
diagram_fact(width, cell_32, 40).
diagram_fact(width, cell_33, 480).
diagram_fact(width, cell_39, 510).
diagram_fact(width, cell_40, 260).
diagram_fact(width, cell_42, 40).
diagram_fact(width, cell_43, 265).
diagram_fact(width, cell_44, 40).
diagram_fact(width, cell_46, 40).
diagram_fact(width, cell_47, 40).
diagram_fact(width, cell_48, 90).
diagram_fact(width, cell_49, 90).
diagram_fact(width, cell_50, 90).
diagram_fact(width, cell_51, 90).
diagram_fact(width, cell_52, 79.6,9).
diagram_fact(width, cell_53, 80.6,3).
diagram_fact(width, cell_54, 112.5).
diagram_fact(width, cell_55, 112.5).
diagram_fact(width, cell_6, 510).
diagram_fact(width, cell_61, 510).
diagram_fact(width, cell_62, 260).
diagram_fact(width, cell_63, 200).
diagram_fact(width, cell_65, 40).
diagram_fact(width, cell_66, 265).
diagram_fact(width, cell_67, 40).
diagram_fact(width, cell_68, 220).
diagram_fact(width, cell_7, 260).
diagram_fact(width, cell_70, 40).
diagram_fact(width, cell_71, 40).
diagram_fact(width, cell_72, 90).
diagram_fact(width, cell_73, 90).
diagram_fact(width, cell_74, 90).
diagram_fact(width, cell_75, 90).
diagram_fact(width, cell_76, 133.4,3).
diagram_fact(width, cell_77, 79.6,9).
diagram_fact(width, cell_78, 80.6,3).
diagram_fact(width, cell_79, 112.5).
diagram_fact(width, cell_8, 200).
diagram_fact(width, cell_80, 112.5).
diagram_fact(width, cell_86, 510).
diagram_fact(width, cell_87, 260).
diagram_fact(width, cell_88, 200).
diagram_fact(width, cell_90, 40).
diagram_fact(width, cell_91, 265).
diagram_fact(width, cell_92, 40).
diagram_fact(width, cell_93, 220).
diagram_fact(width, cell_95, 40).
diagram_fact(width, cell_96, 40).
diagram_fact(width, cell_97, 90).
diagram_fact(width, cell_98, 90).
diagram_fact(width, cell_99, 90).
diagram_fact(x, cell_10, 470).
diagram_fact(x, cell_100, 325).
diagram_fact(x, cell_101, 290).
diagram_fact(x, cell_102, 340.4,6).
diagram_fact(x, cell_103, 210.3,1).
diagram_fact(x, cell_104, 491.2,5).
diagram_fact(x, cell_105, 116.8,8).
diagram_fact(x, cell_11, 305).
diagram_fact(x, cell_111, 120).
diagram_fact(x, cell_112, 230).
diagram_fact(x, cell_114, 470).
diagram_fact(x, cell_115, 305).
diagram_fact(x, cell_116, 285).
diagram_fact(x, cell_118, 100).
diagram_fact(x, cell_119, 210).
diagram_fact(x, cell_12, 285).
diagram_fact(x, cell_120, 70).
diagram_fact(x, cell_121, 580).
diagram_fact(x, cell_122, 325).
diagram_fact(x, cell_123, 325).
diagram_fact(x, cell_124, 70).
diagram_fact(x, cell_13, 330).
diagram_fact(x, cell_15, 100).
diagram_fact(x, cell_16, 210).
diagram_fact(x, cell_22, 120).
diagram_fact(x, cell_23, 230).
diagram_fact(x, cell_24, 260).
diagram_fact(x, cell_26, 470).
diagram_fact(x, cell_27, 305).
diagram_fact(x, cell_28, 285).
diagram_fact(x, cell_29, 330).
diagram_fact(x, cell_31, 100).
diagram_fact(x, cell_32, 210).
diagram_fact(x, cell_33, 140).
diagram_fact(x, cell_39, 120).
diagram_fact(x, cell_40, 230).
diagram_fact(x, cell_42, 470).
diagram_fact(x, cell_43, 305).
diagram_fact(x, cell_44, 285).
diagram_fact(x, cell_46, 100).
diagram_fact(x, cell_47, 210).
diagram_fact(x, cell_48, 70).
diagram_fact(x, cell_49, 580).
diagram_fact(x, cell_50, 325).
diagram_fact(x, cell_51, 325).
diagram_fact(x, cell_52, 340.4,6).
diagram_fact(x, cell_53, 210.3,1).
diagram_fact(x, cell_54, 491.2,5).
diagram_fact(x, cell_55, 116.8,8).
diagram_fact(x, cell_6, 120).
diagram_fact(x, cell_61, 120).
diagram_fact(x, cell_62, 230).
diagram_fact(x, cell_63, 260).
diagram_fact(x, cell_65, 470).
diagram_fact(x, cell_66, 305).
diagram_fact(x, cell_67, 285).
diagram_fact(x, cell_68, 330).
diagram_fact(x, cell_7, 230).
diagram_fact(x, cell_70, 100).
diagram_fact(x, cell_71, 210).
diagram_fact(x, cell_72, 70).
diagram_fact(x, cell_73, 580).
diagram_fact(x, cell_74, 325).
diagram_fact(x, cell_75, 325).
diagram_fact(x, cell_76, 371.4,2).
diagram_fact(x, cell_77, 340.4,6).
diagram_fact(x, cell_78, 215.3,1).
diagram_fact(x, cell_79, 491.2,5).
diagram_fact(x, cell_8, 260).
diagram_fact(x, cell_80, 116.8,8).
diagram_fact(x, cell_86, 120).
diagram_fact(x, cell_87, 230).
diagram_fact(x, cell_88, 260).
diagram_fact(x, cell_90, 470).
diagram_fact(x, cell_91, 305).
diagram_fact(x, cell_92, 285).
diagram_fact(x, cell_93, 330).
diagram_fact(x, cell_95, 100).
diagram_fact(x, cell_96, 210).
diagram_fact(x, cell_97, 70).
diagram_fact(x, cell_98, 580).
diagram_fact(x, cell_99, 325).
diagram_fact(y, cell_10, 265).
diagram_fact(y, cell_100, 425).
diagram_fact(y, cell_101, 120).
diagram_fact(y, cell_102, 245.1,6).
diagram_fact(y, cell_103, 450).
diagram_fact(y, cell_104, 278.7,5).
diagram_fact(y, cell_105, 279.3,8).
diagram_fact(y, cell_11, 450).
diagram_fact(y, cell_111, 170).
diagram_fact(y, cell_112, 220).
diagram_fact(y, cell_114, 265).
diagram_fact(y, cell_115, 450).
diagram_fact(y, cell_116, 482.5).
diagram_fact(y, cell_118, 265).
diagram_fact(y, cell_119, 265).
diagram_fact(y, cell_12, 482.5).
diagram_fact(y, cell_120, 305).
diagram_fact(y, cell_121, 140).
diagram_fact(y, cell_122, "-45").
diagram_fact(y, cell_123, 425).
diagram_fact(y, cell_124, "-95").
diagram_fact(y, cell_13, 487.5).
diagram_fact(y, cell_15, 265).
diagram_fact(y, cell_16, 265).
diagram_fact(y, cell_22, 170).
diagram_fact(y, cell_23, 220).
diagram_fact(y, cell_24, 265).
diagram_fact(y, cell_26, 265).
diagram_fact(y, cell_27, 450).
diagram_fact(y, cell_28, 482.5).
diagram_fact(y, cell_29, 487.5).
diagram_fact(y, cell_31, 265).
diagram_fact(y, cell_32, 265).
diagram_fact(y, cell_33, 190).
diagram_fact(y, cell_39, 170).
diagram_fact(y, cell_40, 220).
diagram_fact(y, cell_42, 265).
diagram_fact(y, cell_43, 450).
diagram_fact(y, cell_44, 482.5).
diagram_fact(y, cell_46, 265).
diagram_fact(y, cell_47, 265).
diagram_fact(y, cell_48, 150).
diagram_fact(y, cell_49, 140).
diagram_fact(y, cell_50, "-45").
diagram_fact(y, cell_51, 425).
diagram_fact(y, cell_52, 245.1,6).
diagram_fact(y, cell_53, 450).
diagram_fact(y, cell_54, 278.7,5).
diagram_fact(y, cell_55, 279.3,8).
diagram_fact(y, cell_6, 170).
diagram_fact(y, cell_61, 170).
diagram_fact(y, cell_62, 220).
diagram_fact(y, cell_63, 265).
diagram_fact(y, cell_65, 265).
diagram_fact(y, cell_66, 450).
diagram_fact(y, cell_67, 485).
diagram_fact(y, cell_68, 487.5).
diagram_fact(y, cell_7, 220).
diagram_fact(y, cell_70, 265).
diagram_fact(y, cell_71, 265).
diagram_fact(y, cell_72, 150).
diagram_fact(y, cell_73, 140).
diagram_fact(y, cell_74, "-45").
diagram_fact(y, cell_75, 425).
diagram_fact(y, cell_76, 362.9,6).
diagram_fact(y, cell_77, 245.1,6).
diagram_fact(y, cell_78, 445).
diagram_fact(y, cell_79, 278.7,5).
diagram_fact(y, cell_8, 265).
diagram_fact(y, cell_80, 279.3,8).
diagram_fact(y, cell_86, 170).
diagram_fact(y, cell_87, 220).
diagram_fact(y, cell_88, 265).
diagram_fact(y, cell_90, 265).
diagram_fact(y, cell_91, 450).
diagram_fact(y, cell_92, 482.5).
diagram_fact(y, cell_93, 487.5).
diagram_fact(y, cell_95, 265).
diagram_fact(y, cell_96, 265).
diagram_fact(y, cell_97, 150).
diagram_fact(y, cell_98, 140).
diagram_fact(y, cell_99, "-45").
